{% set name = "dlib" %}
{% set version = "19.21.0" %}
{% set tag = "v" ~ ".".join(version.split(".")[:2]) %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e79d8e14171b8446d6b5434d7dc3b44a23ca05c8f99266acaf731cc7b268edb6

  patches:
    - 0001-lapack_sgetrf.patch      # [unix]
    - 0002-cxx11_detection.patch
    - 0003-setup_cmake_args.patch
    - 0004-Update-CUDA-tests.patch
    - 0005-Update-CUDA-CMakeLists.patch

build:
  skip: true  # [win and py<35 or (linux and (cuda_compiler_version != "None" and cuda_compiler_version != "10.2"))]
  number: 1
  run_exports:
    - {{ pin_subpackage('dlib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
{% if cuda_compiler_version != "None" %}
    - {{ compiler('cuda') }}
{% endif %}
  host:
    - jpeg
    - libcblas  # [not win]
    - liblapack   # [not win]
    - libpng
    - numpy
    - pip
    - pybind11
    - python
    - sqlite  # [not win]
{% if cuda_compiler_version == "None" %}
    - _dlib_mutex * cpu
{% else %}
    - _dlib_mutex * cuda
    - cudnn
  run_constrained:
    - __cuda {{ cuda_compiler_version }}
{% endif %}

  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  files:
    - test_data/face.jpg
    - test_data/face.png
    - test_data/images.xml
    # contains test configurations including some skips for missiing fixtures
    - setup.cfg
  source_files:
    - tools/python/test
  requires:
    - more-itertools
    - pillow
    - pip
    - pytest
    - pytest-azurepipelines
    - tqdm

  imports:
    - dlib

  commands:
    - python -m pip check
    - python -m pytest tools/python/test

outputs:
  - name: {{ name }}
  - name: {{ name }}-cuda  # [cuda_compiler_version != "None"]
  - name: {{ name }}-cpu   # [cuda_compiler_version == "None"]
    script: noop.py
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage(name, exact=True) }}


about:
  home: http://dlib.net
  license: BSL-1.0
  license_file: dlib/LICENSE.txt
  summary: toolkit for making real world machine learning and data analysis applications
  dev_url: https://github.com/davisking/dlib
  doc_source_url: https://github.com/davisking/dlib/tree/{{ tag }}/docs
  description: |-
    Dlib is a modern C++ toolkit containing machine learning algorithms and tools
    for creating complex software in C++ to solve real world problems. See
    http://dlib.net for the main project documentation and API reference.

extra:
  recipe-maintainers:
    - patricksnape
    - aldanor
